openapi: 3.1.0
info:
  title: C2V+ RAMS Generator
  description: Generates a site-specific RAMS document in sections using a Word template and 20 tailored inputs. Used for United Utilities projects under C2V+.
  version: 1.1.0

servers:
  - url: https://rams-gpt-backend.onrender.com

paths:
  /generate_risk_assessment:
    post:
      operationId: generateRiskAssessment
      summary: Append Risk Assessment section to the master RAMS document
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - content
              properties:
                content:
                  type: string
                  description: Risk Assessment section text
      responses:
        '200':
          description: Updated .docx with Risk Assessment section
          content:
            application/vnd.openxmlformats-officedocument.wordprocessingml.document:
              schema:
                type: string
                format: binary

  /generate_sequence:
    post:
      operationId: generateSequence
      summary: Append Sequence of Activities section to the master RAMS document
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - content
              properties:
                content:
                  type: string
                  description: Sequence of Activities section text
      responses:
        '200':
          description: Updated .docx with Sequence of Activities
          content:
            application/vnd.openxmlformats-officedocument.wordprocessingml.document:
              schema:
                type: string
                format: binary

  /generate_method_statement:
    post:
      operationId: generateMethodStatement
      summary: Append Method Statement section to the master RAMS document
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - content
              properties:
                content:
                  type: string
                  description: Method Statement section text
      responses:
        '200':
          description: Final .docx with Method Statement added
          content:
            application/vnd.openxmlformats-officedocument.wordprocessingml.document:
              schema:
                type: string
                format: binary
