openapi: 3.1.0
info:
  title: C2V+ RAMS Generator
  description: Creates a fully formatted, site-specific RAMS document using a master Word template and 20 tailored inputs, for use on United Utilities wastewater projects under C2V+.
  version: 1.0.0

servers:
  - url: https://rams-gpt-backend.onrender.com

paths:
  /generate_rams:
    post:
      operationId: generateRAMS
      summary: Generate a fully populated RAMS document from a blank Word template and user input
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - answers
                - template_rams
              properties:
                answers:
                  type: string
                  description: JSON-encoded answers to the 20 RAMS questions (covering scope, site, permits, risks, roles, tools, etc.)
                sample_rams1:
                  type: string
                  format: binary
                  description: Completed RAMS example – for reference only
                sample_rams2:
                  type: string
                  format: binary
                sample_rams3:
                  type: string
                  format: binary
                template_rams:
                  type: string
                  format: binary
                  description: The blank master RAMS template (must include placeholders like [Enter Method Statement Here])
                ceswi_7:
                  type: string
                  format: binary
                  description: CESWI 7 reference document
                uuceswi_issue_7:
                  type: string
                  format: binary
                  description: UUCESWI Issue 7 amendments
                what_good_looks_like:
                  type: string
                  format: binary
                  description: VolkerStevin Site Standards – “What Good Looks Like”
                reference_pack:
                  type: string
                  format: binary
                  description: Additional HSE reference documents (Confined Space Regs, LOLER, PUWER, WIMES, etc.)
      responses:
        '200':
          description: RAMS document generated successfully
          content:
            application/vnd.openxmlformats-officedocument.wordprocessingml.document:
              schema:
                type: string
                format: binary
